#!/usr/bin/env python3

import argparse
import csv
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt


# ============================================================
# ARGUMENTS
# ============================================================

def parse_args():
    p = argparse.ArgumentParser(
        description=(
            "Combine Frobenius norm, stable rank, numerical rank, "
            "and optionally downstream accuracy for multiple backbones."
        )
    )

    p.add_argument(
        "--run",
        action="append",
        required=True,
        help=(
            "Measurement run in the form "
            "'label:path:color'. "
            "Example: "
            "'Collapsed by WD:FINAL_RankMeas/collapsed_highWD5e3:green'. "
            "May be passed multiple times."
        ),
    )

    p.add_argument(
        "--out-dir",
        required=True,
        help="Directory for combined plots.",
    )

    p.add_argument(
        "--accuracy-root",
        default=None,
        help=(
            "Optional root containing accuracyFINAL5 condition "
            "directories."
        ),
    )

    p.add_argument(
        "--accuracy-map",
        action="append",
        default=[],
        help=(
            "Optional mapping from rank label to accuracy condition. "
            "Format: 'rank label=condition_dir'. "
            "May be passed multiple times."
        ),
    )

    p.add_argument(
        "--title",
        default="Backbone Weight Geometry Across Network Depth",
        help="Base plot title.",
    )

    return p.parse_args()


# ============================================================
# PARSE RUN SPECIFICATION
# ============================================================

def parse_run_spec(spec):
    """
    Format:

        label:path:color

    Split from the right twice so labels may contain spaces.
    """

    parts = spec.rsplit(":", 2)

    if len(parts) != 3:
        raise ValueError(
            f"Invalid --run specification:\n{spec}\n"
            "Expected: label:path:color"
        )

    label, path, color = parts

    return {
        "label": label,
        "path": Path(path),
        "color": color,
    }


# ============================================================
# LOAD rank/norm JSON
# ============================================================

def load_raw_stats(run_dir: Path):
    """
    Read rawText.json generated by measureRankAndNorms.py.

    Expected structure:

        {
            "0": {
                "layer": "...",
                "fro": ...,
                "sr": ...,
                "r": ...,
                "ws": [...]
            },
            ...
        }
    """

    import json

    path = run_dir / "rawText.json"

    if not path.is_file():
        raise FileNotFoundError(
            f"Missing rawText.json:\n  {path}"
        )

    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)

    # Preserve numerical insertion order from the measurement script.
    ordered_keys = sorted(
        raw.keys(),
        key=lambda x: int(x)
    )

    result = {}

    for key in ordered_keys:
        entry = raw[key]

        layer = entry["layer"]

        result[layer] = {
            "fro": float(entry["fro"]),
            "sr": float(entry["sr"]),
            "rank": int(entry["r"]),
            "shape": tuple(entry["ws"]),
        }

    return result


# ============================================================
# SHORT DISPLAY NAMES
# ============================================================

def short_layer_name(layer):
    """
    Make long PyTorch module names more readable.
    """

    return (
        layer
        .replace("_feature_blocks.", "")
        .replace(".shortcut.0", ".sc")
        .replace("block", "b")
        .replace("conv", "c")
    )


# ============================================================
# VALIDATE / ALIGN LAYERS
# ============================================================

def align_runs(runs):
    """
    Use first run as reference layer ordering.

    All other runs must contain those layers.
    """

    first_label = next(iter(runs))
    layers = list(runs[first_label].keys())

    for label, stats in runs.items():

        missing = [
            layer
            for layer in layers
            if layer not in stats
        ]

        if missing:
            raise RuntimeError(
                f"{label} is missing layers:\n"
                + "\n".join(missing)
            )

    return layers


# ============================================================
# STAGE BOUNDARIES
# ============================================================

def find_stage_boundaries(layers):
    """
    Detect boundaries between _feature_blocks.N stages.
    """

    bounds = []

    previous_stage = None

    for i, layer in enumerate(layers):

        m = re.search(
            r"_feature_blocks\.(\d+)",
            layer
        )

        stage = (
            int(m.group(1))
            if m
            else None
        )

        if (
            i > 0
            and stage is not None
            and previous_stage is not None
            and stage != previous_stage
        ):
            bounds.append(i)

        if stage is not None:
            previous_stage = stage

    return bounds


# ============================================================
# ACCURACY CSV
# ============================================================

def find_accuracy_csv(condition_dir: Path):

    csvs = sorted(
        condition_dir.glob("*.csv")
    )

    if not csvs:
        raise FileNotFoundError(
            f"No accuracy CSV found in:\n"
            f"  {condition_dir}"
        )

    return csvs[0]


def read_accuracy_csv(path: Path):

    data = {}

    with open(
        path,
        "r",
        encoding="utf-8"
    ) as f:

        reader = csv.DictReader(f)

        for row in reader:

            data[row["network_key"]] = {
                "mean": float(row["mean"]),
                "std": float(row["std_dev"]),
            }

    return data


# ============================================================
# MAP FEATURE PROBE -> WEIGHT LAYER
# ============================================================

def probe_to_weight_layer(probe):
    """
    Map downstream representation feature keys to the weight
    layer most naturally associated with them.

    Examples:

        conv1.Stem_Conv
          -> _feature_blocks.0.Stem_Conv

        conv2.block0
          -> _feature_blocks.1.block0.conv2

        conv3.block2
          -> _feature_blocks.2.block2.conv2
    """

    if probe == "conv1.Stem_Conv":
        return "_feature_blocks.0.Stem_Conv"

    m = re.fullmatch(
        r"conv(\d+)\.block(\d+)",
        probe
    )

    if m:

        stage = int(m.group(1))
        block = int(m.group(2))

        return (
            f"_feature_blocks.{stage - 1}."
            f"block{block}.conv2"
        )

    return None


# ============================================================
# LOAD ACCURACY DATA
# ============================================================

def load_accuracy_points(
    accuracy_root,
    accuracy_condition,
    layers,
):
    """
    Return:

        [(x_index, mean, std, probe_name), ...]
    """

    condition_dir = (
        Path(accuracy_root)
        / accuracy_condition
    )

    csv_path = find_accuracy_csv(
        condition_dir
    )

    acc_data = read_accuracy_csv(
        csv_path
    )

    points = []

    for probe, vals in acc_data.items():

        weight_layer = probe_to_weight_layer(
            probe
        )

        if weight_layer not in layers:
            continue

        x_idx = layers.index(
            weight_layer
        )

        points.append(
            (
                x_idx,
                vals["mean"],
                vals["std"],
                probe,
            )
        )

    return sorted(
        points,
        key=lambda x: x[0]
    )


# ============================================================
# DRAW ONE RANK METRIC
# ============================================================

def draw_metric(
    ax,
    runs,
    run_specs,
    layers,
    metric,
    ylabel,
    bounds,
):
    """
    Draw one geometry metric for all models.
    """

    x = list(range(len(layers)))

    for spec in run_specs:

        label = spec["label"]
        color = spec["color"]

        values = [
            runs[label][layer][metric]
            for layer in layers
        ]

        ax.plot(
            x,
            values,
            marker="o",
            markersize=4,
            linewidth=2,
            color=color,
            label=label,
        )

    # Numerical rank ceiling
    if metric == "rank":

        max_rank = [
            min(runs[run_specs[0]["label"]][layer]["shape"])
            for layer in layers
        ]

        ax.plot(
            x,
            max_rank,
            linestyle="--",
            linewidth=1.5,
            color="gray",
            label="Maximum possible rank",
        )

    for boundary in bounds:
        ax.axvline(
            boundary - 0.5,
            linewidth=1,
            color="lightgray",
        )

    ax.set_ylabel(
        ylabel
    )

    ax.grid(
        True,
        axis="y",
        alpha=0.3,
    )

    ax.set_axisbelow(True)


# ============================================================
# DRAW ACCURACY PANEL
# ============================================================

def draw_accuracy_panel(
    ax,
    run_specs,
    accuracy_points,
    bounds,
):
    """
    Draw downstream validation accuracy.

    Line = mean
    translucent region = +/- std
    """

    for spec in run_specs:

        label = spec["label"]
        color = spec["color"]

        if label not in accuracy_points:
            continue

        pts = accuracy_points[label]

        if not pts:
            continue

        xs = [
            p[0]
            for p in pts
        ]

        means = [
            p[1]
            for p in pts
        ]

        stds = [
            p[2]
            for p in pts
        ]

        lower = [
            m - s
            for m, s in zip(means, stds)
        ]

        upper = [
            m + s
            for m, s in zip(means, stds)
        ]

        ax.plot(
            xs,
            means,
            marker="o",
            markersize=5,
            linewidth=2,
            color=color,
            label=label,
        )

        ax.fill_between(
            xs,
            lower,
            upper,
            color=color,
            alpha=0.12,
            linewidth=0,
        )

    for boundary in bounds:
        ax.axvline(
            boundary - 0.5,
            linewidth=1,
            color="lightgray",
        )

    ax.set_ylabel(
        "Validation Top-1 (%)"
    )

    ax.grid(
        True,
        axis="y",
        alpha=0.3,
    )

    ax.set_axisbelow(True)


# ============================================================
# COMMON X AXIS
# ============================================================

def finish_axes(
    fig,
    axes,
    layers,
):
    x = list(range(len(layers)))

    short = [
        short_layer_name(layer)
        for layer in layers
    ]

    axes[-1].set_xticks(x)

    axes[-1].set_xticklabels(
        short,
        rotation=90,
        fontsize=7,
    )

    axes[-1].set_xlabel(
        "Backbone weight layer"
    )

    fig.tight_layout()


# ============================================================
# MAIN
# ============================================================

def main():

    args = parse_args()

    run_specs = [
        parse_run_spec(spec)
        for spec in args.run
    ]

    out_dir = Path(
        args.out_dir
    )

    out_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    # --------------------------------------------------------
    # Load all rank measurements
    # --------------------------------------------------------

    runs = {}

    for spec in run_specs:

        label = spec["label"]

        print(
            f"Loading {label}: "
            f"{spec['path']}"
        )

        runs[label] = load_raw_stats(
            spec["path"]
        )


    layers = align_runs(
        runs
    )

    bounds = find_stage_boundaries(
        layers
    )


    # ========================================================
    # THREE-PANEL GEOMETRY PLOT
    # ========================================================

    metrics = [
        ("fro", "Frobenius Norm"),
        ("sr", "Stable Rank"),
        ("rank", "Numerical Rank"),
    ]

    fig, axes = plt.subplots(
        3,
        1,
        figsize=(16, 12),
        sharex=True,
    )

    fig.suptitle(
        args.title,
        fontsize=16,
    )

    for ax, (metric, ylabel) in zip(
        axes,
        metrics
    ):

        draw_metric(
            ax=ax,
            runs=runs,
            run_specs=run_specs,
            layers=layers,
            metric=metric,
            ylabel=ylabel,
            bounds=bounds,
        )

        ax.legend(
            fontsize=8,
            loc="best",
        )

    finish_axes(
        fig,
        axes,
        layers,
    )

    path = (
        out_dir
        / "rank_metrics_comparison.png"
    )

    fig.savefig(
        path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(fig)

    print(
        f"Saved {path}"
    )


    # ========================================================
    # OPTIONAL ACCURACY DATA
    # ========================================================

    if args.accuracy_root:

        acc_map = {}

        for item in args.accuracy_map:

            if "=" not in item:
                raise ValueError(
                    f"Invalid --accuracy-map: {item}"
                )

            label, condition = item.split(
                "=",
                1
            )

            acc_map[label] = condition


        accuracy_points = {}

        for spec in run_specs:

            label = spec["label"]

            if label not in acc_map:
                print(
                    f"No accuracy mapping for "
                    f"{label}; skipping."
                )
                continue

            accuracy_points[label] = (
                load_accuracy_points(
                    accuracy_root=args.accuracy_root,
                    accuracy_condition=acc_map[label],
                    layers=layers,
                )
            )


        # ====================================================
        # FOUR-PANEL GEOMETRY + ACCURACY
        # ====================================================

        fig, axes = plt.subplots(
            4,
            1,
            figsize=(16, 15),
            sharex=True,
        )

        fig.suptitle(
            args.title
            + "\nwith Downstream Transfer Accuracy",
            fontsize=16,
        )


        for ax, (metric, ylabel) in zip(
            axes[:3],
            metrics
        ):

            draw_metric(
                ax=ax,
                runs=runs,
                run_specs=run_specs,
                layers=layers,
                metric=metric,
                ylabel=ylabel,
                bounds=bounds,
            )

            ax.legend(
                fontsize=8,
                loc="best",
            )


        draw_accuracy_panel(
            ax=axes[3],
            run_specs=run_specs,
            accuracy_points=accuracy_points,
            bounds=bounds,
        )

        axes[3].legend(
            fontsize=8,
            loc="best",
        )

        finish_axes(
            fig,
            axes,
            layers,
        )

        path = (
            out_dir
            / "rank_metrics_comparison_with_accuracy.png"
        )

        fig.savefig(
            path,
            dpi=300,
            bbox_inches="tight",
        )

        plt.close(fig)

        print(
            f"Saved {path}"
        )


if __name__ == "__main__":
    main()