#!/usr/bin/env python3

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


# ============================================================
# CONDITION DEFINITIONS
# ============================================================

CONDITIONS = {
    "collapsedWD": {
        "label": "Collapsed by WD",
        "color": "green",
    },
    "collapsedRegs": {
        "label": "Collapsed by Regs",
        "color": "blue",
    },
    "notcollapsedNOWD": {
        "label": "Not Collapsed — No WD",
        "color": "purple",
    },
    "notcollapsedRegs": {
        "label": "Not Collapsed — Regs",
        "color": "red",
    },
}


# ============================================================
# CSV READING
# ============================================================

def find_csv(condition_dir: Path):
    """
    Find the accuracy CSV inside one condition directory.
    """

    csv_files = sorted(condition_dir.glob("*.csv"))

    if not csv_files:
        raise FileNotFoundError(
            f"No CSV found in {condition_dir}"
        )

    if len(csv_files) > 1:
        print(
            f"WARNING: Multiple CSVs found in {condition_dir}. "
            f"Using {csv_files[0].name}"
        )

    return csv_files[0]


def read_accuracy_csv(path: Path):
    """
    Read CSV generated by updatedAccs.py.

    Expected columns:

        network_key
        n
        mean
        std_dev
        run1
        run2
        ...

    Returns:
        list of dictionaries
    """

    rows = []

    with open(path, "r", encoding="utf-8") as f:

        reader = csv.DictReader(f)

        required = {
            "network_key",
            "mean",
            "std_dev",
        }

        missing = required - set(reader.fieldnames or [])

        if missing:
            raise ValueError(
                f"{path} is missing required columns: {missing}"
            )

        for row in reader:

            rows.append(
                {
                    "network_key": row["network_key"],
                    "mean": float(row["mean"]),
                    "std": float(row["std_dev"]),
                }
            )

    return rows


# ============================================================
# DATA ALIGNMENT
# ============================================================

def align_conditions(data):
    """
    Make sure all conditions use the same network-layer order.

    The first condition establishes the x-axis ordering.

    Raises an error if another experiment is missing layers.
    """

    first_condition = next(iter(data))

    reference_layers = [
        row["network_key"]
        for row in data[first_condition]
    ]

    aligned = {}

    for condition, rows in data.items():

        by_layer = {
            row["network_key"]: row
            for row in rows
        }

        missing = [
            layer
            for layer in reference_layers
            if layer not in by_layer
        ]

        if missing:
            raise ValueError(
                f"{condition} is missing network layers:\n"
                + "\n".join(missing)
            )

        aligned[condition] = [
            by_layer[layer]
            for layer in reference_layers
        ]

    return reference_layers, aligned


# ============================================================
# PLOTTING
# ============================================================

def plot_comparison(
    data,
    output_path: Path,
    title: str,
):
    """
    Plot mean top-1 accuracy across network depth.

    Each condition:
        line = mean top-1 accuracy
        shaded region = mean +/- 1 std

    Only the best layer from each condition receives a large
    open circle and annotation.
    """

    layers, aligned = align_conditions(data)

    x = list(range(len(layers)))

    fig, ax = plt.subplots(
        figsize=(19, 9)
    )

    # Used later to determine a good tight y-axis
    all_lower = []
    all_upper = []


    # ========================================================
    # Draw each experiment
    # ========================================================

    for condition, settings in CONDITIONS.items():

        rows = aligned[condition]

        means = [
            row["mean"]
            for row in rows
        ]

        stds = [
            row["std"]
            for row in rows
        ]

        lower = [
            avg - std
            for avg, std in zip(means, stds)
        ]

        upper = [
            avg + std
            for avg, std in zip(means, stds)
        ]

        all_lower.extend(lower)
        all_upper.extend(upper)


        # ----------------------------------------------------
        # Mean accuracy line
        # ----------------------------------------------------

        ax.plot(
            x,
            means,
            color=settings["color"],
            linewidth=2.4,
            marker="o",
            markersize=5,
            label=settings["label"],
            zorder=3,
        )


        # ----------------------------------------------------
        # Standard deviation region
        #
        # Same color as line, translucent.
        # Represents mean +/- 1 std.
        # ----------------------------------------------------

        ax.fill_between(
            x,
            lower,
            upper,
            color=settings["color"],
            alpha=0.12,
            linewidth=0,
            zorder=1,
        )


        # ----------------------------------------------------
        # Find ONLY the best layer
        # ----------------------------------------------------

        best_idx = max(
            range(len(means)),
            key=lambda i: means[i]
        )

        best_mean = means[best_idx]
        best_std = stds[best_idx]
        best_layer = layers[best_idx]


        # ----------------------------------------------------
        # Circle the best point
        #
        # Large unfilled circle in the experiment's color.
        # ----------------------------------------------------

        ax.scatter(
            [best_idx],
            [best_mean],
            s=260,
            facecolors="none",
            edgecolors=settings["color"],
            linewidths=3.0,
            zorder=6,
        )


        # Additional thin black outer circle to make the
        # selected point stand out against its std band.
        ax.scatter(
            [best_idx],
            [best_mean],
            s=330,
            facecolors="none",
            edgecolors="black",
            linewidths=1.0,
            zorder=5,
        )


        # ----------------------------------------------------
        # Annotate ONLY the best point
        # ----------------------------------------------------

        ax.annotate(
            f"{settings['label']}\n"
            f"{best_layer}\n"
            f"{best_mean:.2f} ± {best_std:.2f}%",
            xy=(best_idx, best_mean),
            xytext=(8, 16),
            textcoords="offset points",
            fontsize=8.5,
            color=settings["color"],
            fontweight="bold",
            ha="left",
            va="bottom",
            zorder=7,
            bbox={
                "boxstyle": "round,pad=0.25",
                "facecolor": "white",
                "edgecolor": settings["color"],
                "alpha": 0.85,
            },
        )


    # ========================================================
    # X axis
    # ========================================================

    ax.set_xticks(x)

    ax.set_xticklabels(
        layers,
        rotation=55,
        ha="right",
        fontsize=9,
    )

    ax.set_xlabel(
        "Representation Depth / Network Layer",
        fontsize=12
    )


    # ========================================================
    # Y axis
    # ========================================================

    ax.set_ylabel(
        "Validation Top-1 Accuracy (%)",
        fontsize=12
    )


    # Tight y-axis so depth-wise differences are visible.
    global_min = min(all_lower)
    global_max = max(all_upper)

    value_range = global_max - global_min

    padding = max(
        value_range * 0.15,
        1.5
    )

    y_min = max(
        0,
        global_min - padding
    )

    y_max = min(
        100,
        global_max + padding
    )

    ax.set_ylim(
        y_min,
        y_max
    )


    # ========================================================
    # Styling
    # ========================================================

    ax.set_title(
        title,
        fontsize=16,
        pad=16,
    )

    ax.grid(
        True,
        axis="y",
        alpha=0.25,
    )

    ax.set_axisbelow(True)

    ax.legend(
        loc="best",
        fontsize=10,
        frameon=True,
    )


    # Explanation of shaded regions
    ax.text(
        0.01,
        0.01,
        "Shaded regions represent mean ± 1 standard deviation across runs.",
        transform=ax.transAxes,
        fontsize=9,
        alpha=0.75,
        ha="left",
        va="bottom",
    )


    # ========================================================
    # Save
    # ========================================================

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    fig.tight_layout()

    fig.savefig(
        output_path,
        dpi=300,
        bbox_inches="tight",
    )

    # Also generate a PDF for publication / LaTeX use
    pdf_path = output_path.with_suffix(".pdf")

    fig.savefig(
        pdf_path,
        bbox_inches="tight",
    )

    plt.close(fig)

    print()
    print(f"PNG saved to: {output_path}")
    print(f"PDF saved to: {pdf_path}")


# ============================================================
# MAIN
# ============================================================

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Compare FINAL5 downstream top-1 accuracy across "
            "network depth for four neural-collapse conditions."
        )
    )

    parser.add_argument(
        "--root",
        default="./accuracyFINAL5",
        help=(
            "Root containing collapsedRegs, collapsedWD, "
            "notcollapsedNOWD, and notcollapsedRegs."
        ),
    )

    parser.add_argument(
        "--output",
        default="./accuracyFINAL5/final_network_comparison.png",
        help="Output PNG path.",
    )

    parser.add_argument(
        "--title",
        default=(
            "Downstream Transfer Accuracy Across "
            "Representation Depth"
        ),
        help="Plot title.",
    )

    args = parser.parse_args()

    root = Path(args.root)

    if not root.exists():
        raise SystemExit(
            f"ERROR: Root directory does not exist: {root}"
        )


    # ========================================================
    # Load all four conditions
    # ========================================================

    data = {}

    for condition in CONDITIONS:

        condition_dir = root / condition

        if not condition_dir.exists():
            raise SystemExit(
                f"ERROR: Missing condition directory: "
                f"{condition_dir}"
            )

        csv_path = find_csv(
            condition_dir
        )

        print(
            f"{condition:<22} -> {csv_path}"
        )

        data[condition] = read_accuracy_csv(
            csv_path
        )


    # ========================================================
    # Print best layer for sanity checking
    # ========================================================

    print()
    print("=" * 75)
    print("BEST DOWNSTREAM REPRESENTATION FOR EACH CONDITION")
    print("=" * 75)

    for condition, settings in CONDITIONS.items():

        best = max(
            data[condition],
            key=lambda row: row["mean"]
        )

        print(
            f"{settings['label']:<28} "
            f"{best['network_key']:<24} "
            f"{best['mean']:.2f} ± {best['std']:.2f}%"
        )

    print("=" * 75)


    # ========================================================
    # Plot
    # ========================================================

    plot_comparison(
        data=data,
        output_path=Path(args.output),
        title=args.title,
    )


if __name__ == "__main__":
    main()